apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vote
  namespace: vote
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: vote.gizabutler.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vote
              servicePort: 5000
    - host: result.gizabutler.com
      http:
        paths:
          - path: /
            backend:
              serviceName: result
              servicePort: 5001
