apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      # version: 1.1.6
      sourceRef:
        kind: HelmRepository
        name: ekscharts
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    serviceAccount:
      name: alb-ingress-controller
      create: false
    ingressClass: alb
    clusterName: eks-sysdig
